#pragma once

class Tag{
    public:
    static int 
                    PRG,
                    BGN,
                    END,
                    INT,
                    DEC,
                    IF,
                    ELSE,
                    DECL,
                    THEN,
                    READ,
                    WRT,
                    DO,
                    WHILE,
                    FOR,
                    MOD,
                    ATRIB,
                    LT,
                    LE,
                    EQ,
                    GT,
                    GE,
                    LL,
                    GG,
                    LLL,
                    GGG,
                    ID,
                    NUM,
                    ADD,
                    SUB,
                    MLT,
                    DIV,
                    PNT,
                    COM,
                    SMC,
                    SQUT,
                    CLM,
                    DQUT,
                    QST,
                    OR,
                    AND,
                    NE,
                    OPAR,
                    CPAR,
                    TRUE,
                    FALSE,
                    EoF;


                    
};